### ISSUE TITLE
キューの一覧表示機能

### ISSUE THREAD

**Issue by 844196** [OsamuMORIMOTO/MyListMove#1]
<blockquote class="twitter-tweet" lang="ja"><p lang="ja" dir="ltr">マイリス枠の　リクエストリストの一覧は　リスナー側にも見える形にしたほうが張る側もうれしいのかな？　なにかWebページに出しておくか　それようのツール作るかしてな</p>&mdash; Osamu_MORIMOTO (@2525morimoto) <a href="https://twitter.com/2525morimoto/status/656862557395750912">2015, 10月 21</a></blockquote>
<script async src="//platform.twitter.com/widgets.js" charset="utf-8"></script>

~~まず`v0.1`のリリースだと思うんですけど~~

`NCV`の仕様が不明なんですが、プラグインはそこまで自由に作れるもんなんですか？

---

あればうれしい
というかコメジェネどこいった

**Comment by OsamuMORIMOTO** [comment]
Webページでやるなら
サーバにファイルを監視させて、そこに書き出してくなり　なんなりで可能かと
ただ　サーバがない

OBSにコメジェネ入れるの面倒なの(デスクトップにおいておくのも邪魔くさい)
そのうちコメジェネも作りましょうかね

**Comment by 844196** [comment]
@OsamuMORIMOTO :sake:
